target_sources(
    advanced_platformer
    PRIVATE
        ${PROJECT_SOURCE_DIR}/app/audio/audio_device.cpp
        ${PROJECT_SOURCE_DIR}/app/audio/audio_playback.cpp
        ${PROJECT_SOURCE_DIR}/app/application.cpp
        ${PROJECT_SOURCE_DIR}/app/application_context.cpp
        ${PROJECT_SOURCE_DIR}/app/debug/console_ui.cpp
        ${PROJECT_SOURCE_DIR}/app/debug/debug_cursor.cpp
        ${PROJECT_SOURCE_DIR}/app/debug/debug_draw.cpp
        ${PROJECT_SOURCE_DIR}/app/debug/debug_overlay_ui.cpp
        ${PROJECT_SOURCE_DIR}/app/debug/debug_tools.cpp
        ${PROJECT_SOURCE_DIR}/app/debug/frame_axes.cpp
        ${PROJECT_SOURCE_DIR}/app/debug/frame_profile_ui.cpp
        ${PROJECT_SOURCE_DIR}/app/debug/frame_selection.cpp
        ${PROJECT_SOURCE_DIR}/app/debug/machine_graph_ui.cpp
        ${PROJECT_SOURCE_DIR}/app/debug/navigation_debug_ui.cpp
        ${PROJECT_SOURCE_DIR}/app/debug/npc_names.cpp
        ${PROJECT_SOURCE_DIR}/app/graphics/display_viewport.cpp
        ${PROJECT_SOURCE_DIR}/app/graphics/game_window.cpp
        ${PROJECT_SOURCE_DIR}/app/graphics/imgui_session.cpp
        ${PROJECT_SOURCE_DIR}/app/graphics/sprite_renderer.cpp
        ${PROJECT_SOURCE_DIR}/app/main.cpp
        ${PROJECT_SOURCE_DIR}/app/session/asset_watcher.cpp
        ${PROJECT_SOURCE_DIR}/app/session/atlas_regions.cpp
        ${PROJECT_SOURCE_DIR}/app/session/content_session.cpp
        ${PROJECT_SOURCE_DIR}/app/session/level_requests.cpp
        ${PROJECT_SOURCE_DIR}/app/session/play_control.cpp
        ${PROJECT_SOURCE_DIR}/app/ui/exit_hint_ui.cpp
        ${PROJECT_SOURCE_DIR}/app/ui/health_hud_ui.cpp
        ${PROJECT_SOURCE_DIR}/app/ui/hud_draw.cpp
        ${PROJECT_SOURCE_DIR}/app/ui/interface_ui.cpp
        ${PROJECT_SOURCE_DIR}/app/ui/inventory_layout.cpp
        ${PROJECT_SOURCE_DIR}/app/ui/inventory_ui.cpp
        ${PROJECT_SOURCE_DIR}/app/ui/pause_ui.cpp
)
