target_sources(
    advanced_platformer_core
    PRIVATE
        ${PROJECT_SOURCE_DIR}/core/src/audio/music.cpp
        ${PROJECT_SOURCE_DIR}/core/src/audio/sound_patch.cpp
        ${PROJECT_SOURCE_DIR}/core/src/audio/sound_mixer.cpp
        ${PROJECT_SOURCE_DIR}/core/src/actor/actor_id.cpp
        ${PROJECT_SOURCE_DIR}/core/src/actor/actor_system.cpp
        ${PROJECT_SOURCE_DIR}/core/src/actor/actor_validation.cpp
        ${PROJECT_SOURCE_DIR}/core/src/actor/lifecycle.cpp
        ${PROJECT_SOURCE_DIR}/core/src/combat/attack_system.cpp
        ${PROJECT_SOURCE_DIR}/core/src/combat/combat.cpp
        ${PROJECT_SOURCE_DIR}/core/src/combat/projectile_system.cpp
        ${PROJECT_SOURCE_DIR}/core/src/input/input_state.cpp
        ${PROJECT_SOURCE_DIR}/core/src/input/input_program.cpp
        ${PROJECT_SOURCE_DIR}/core/src/inventory/inventory.cpp
        ${PROJECT_SOURCE_DIR}/core/src/inventory/item.cpp
        ${PROJECT_SOURCE_DIR}/core/src/inventory/item_use.cpp
        ${PROJECT_SOURCE_DIR}/core/src/level/level_generator.cpp
        ${PROJECT_SOURCE_DIR}/core/src/level/room_pieces.cpp
        ${PROJECT_SOURCE_DIR}/core/src/math/aabb.cpp
        ${PROJECT_SOURCE_DIR}/core/src/math/coordinates.cpp
        ${PROJECT_SOURCE_DIR}/core/src/math/validation.cpp
        ${PROJECT_SOURCE_DIR}/core/src/movement/flying_movement.cpp
        ${PROJECT_SOURCE_DIR}/core/src/movement/platformer_movement.cpp
        ${PROJECT_SOURCE_DIR}/core/src/movement/pounce.cpp
        ${PROJECT_SOURCE_DIR}/core/src/movement/surface_climb.cpp
        ${PROJECT_SOURCE_DIR}/core/src/navigation/actor_navigation.cpp
        ${PROJECT_SOURCE_DIR}/core/src/navigation/navigation_fill.cpp
        ${PROJECT_SOURCE_DIR}/core/src/navigation/path_follower.cpp
        ${PROJECT_SOURCE_DIR}/core/src/navigation/platformer_cells.cpp
        ${PROJECT_SOURCE_DIR}/core/src/navigation/platformer_connection_cache.cpp
        ${PROJECT_SOURCE_DIR}/core/src/navigation/platformer_connections.cpp
        ${PROJECT_SOURCE_DIR}/core/src/navigation/route_search.cpp
        ${PROJECT_SOURCE_DIR}/core/src/npc/npc_activity_runner.cpp
        ${PROJECT_SOURCE_DIR}/core/src/npc/npc_senses.cpp
        ${PROJECT_SOURCE_DIR}/core/src/npc/npc_system.cpp
        ${PROJECT_SOURCE_DIR}/core/src/npc/npc_fact_rows.cpp
        ${PROJECT_SOURCE_DIR}/core/src/npc/npc_facts.cpp
        ${PROJECT_SOURCE_DIR}/core/src/npc/npc_navigation.cpp
        ${PROJECT_SOURCE_DIR}/core/src/npc/npc_state_machine.cpp
        ${PROJECT_SOURCE_DIR}/core/src/physics/body.cpp
        ${PROJECT_SOURCE_DIR}/core/src/physics/collision.cpp
        ${PROJECT_SOURCE_DIR}/core/src/physics/segment_cast.cpp
        ${PROJECT_SOURCE_DIR}/core/src/render/actor_sprite.cpp
        ${PROJECT_SOURCE_DIR}/core/src/render/animation.cpp
        ${PROJECT_SOURCE_DIR}/core/src/render/animation_system.cpp
        ${PROJECT_SOURCE_DIR}/core/src/render/cover_fade.cpp
        ${PROJECT_SOURCE_DIR}/core/src/render/presentation.cpp
        ${PROJECT_SOURCE_DIR}/core/src/render/camera.cpp
        ${PROJECT_SOURCE_DIR}/core/src/render/render_scene.cpp
        ${PROJECT_SOURCE_DIR}/core/src/render/sprite.cpp
        ${PROJECT_SOURCE_DIR}/core/src/timing/fixed_step.cpp
        ${PROJECT_SOURCE_DIR}/core/src/timing/frame_profile.cpp
        ${PROJECT_SOURCE_DIR}/core/src/timing/stopwatch.cpp
        ${PROJECT_SOURCE_DIR}/core/src/world/tile_map.cpp
        ${PROJECT_SOURCE_DIR}/core/src/world/world.cpp
        ${PROJECT_SOURCE_DIR}/core/src/world/level_exit.cpp
        ${PROJECT_SOURCE_DIR}/core/src/world/level_validation.cpp
        ${PROJECT_SOURCE_DIR}/core/src/world/pickup.cpp
        ${PROJECT_SOURCE_DIR}/core/src/world/sight.cpp
        ${PROJECT_SOURCE_DIR}/core/src/world/world_requests.cpp
        ${PROJECT_SOURCE_DIR}/core/src/world/world_simulation.cpp
)
