target_sources(
    advanced_platformer_tests
    PRIVATE
        ${PROJECT_SOURCE_DIR}/app/application_context.cpp
        ${PROJECT_SOURCE_DIR}/app/debug/debug_cursor.cpp
        ${PROJECT_SOURCE_DIR}/app/debug/frame_axes.cpp
        ${PROJECT_SOURCE_DIR}/app/debug/frame_selection.cpp
        ${PROJECT_SOURCE_DIR}/app/graphics/display_viewport.cpp
        ${PROJECT_SOURCE_DIR}/app/session/asset_watcher.cpp
        ${PROJECT_SOURCE_DIR}/app/session/atlas_regions.cpp
        ${PROJECT_SOURCE_DIR}/app/session/level_requests.cpp
        ${PROJECT_SOURCE_DIR}/app/session/play_control.cpp
        ${PROJECT_SOURCE_DIR}/app/ui/inventory_layout.cpp
        ${PROJECT_SOURCE_DIR}/playtest/playtest.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/actor/test_actor_system.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/actor/test_lifecycle.cpp
        ${PROJECT_SOURCE_DIR}/tests/app/debug/test_debug_cursor.cpp
        ${PROJECT_SOURCE_DIR}/tests/app/debug/test_frame_axes.cpp
        ${PROJECT_SOURCE_DIR}/tests/app/debug/test_frame_selection.cpp
        ${PROJECT_SOURCE_DIR}/tests/app/graphics/test_display_viewport.cpp
        ${PROJECT_SOURCE_DIR}/tests/app/session/test_asset_watcher.cpp
        ${PROJECT_SOURCE_DIR}/tests/app/session/test_atlas_regions.cpp
        ${PROJECT_SOURCE_DIR}/tests/app/session/test_level_requests.cpp
        ${PROJECT_SOURCE_DIR}/tests/app/session/test_play_control.cpp
        ${PROJECT_SOURCE_DIR}/tests/app/test_application_context.cpp
        ${PROJECT_SOURCE_DIR}/tests/app/ui/test_inventory_layout.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/combat/test_bite_attack.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/combat/test_contact_damage.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/combat/test_projectile_system.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/combat/test_ranged_attack.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_actor_catalog.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_actor_definition.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_animation_catalog.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_camera_settings.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_content_glaze.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_content_integrity.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_content_validation.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_exit_catalog.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_hud_catalog.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_item_catalog.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_machine_catalog.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_npc_script_catalog.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_pickup_catalog.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_room_piece_pickups.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_room_piece_routes.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_room_pieces.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/content/test_tile_catalog.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/diagnostics/test_console_log.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/diagnostics/test_debug_overlay.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/diagnostics/test_debug_overlay_machine.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/diagnostics/test_debug_overlay_navigation.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/diagnostics/test_game_debug.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/diagnostics/test_navigation_debug.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/level/test_generated_level.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/level/test_level_composition.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/level/test_level_object_composition.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/level/test_level_reload.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/level/test_level_transition.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/test_game_presentation.cpp
        ${PROJECT_SOURCE_DIR}/tests/game/test_game_reload.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/input/test_input_program.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/input/test_input_state.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/level/test_level_generator.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/inventory/test_inventory.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/math/test_coordinates.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/math/test_validation.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/movement/test_flying_movement.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/movement/test_platformer_movement.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/movement/test_pounce.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/movement/test_surface_climb.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/navigation/test_actor_navigation.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/navigation/test_navigation_fill.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/navigation/test_path_follower.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/navigation/test_platformer_cells.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/navigation/test_platformer_connection_cache.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/navigation/test_platformer_connection_cache_invalidation.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/navigation/test_platformer_connections.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/navigation/test_route_search.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/npc/test_npc_activity_runner.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/npc/test_npc_facts.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/npc/test_npc_navigation.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/npc/test_npc_senses.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/npc/test_npc_state_machine.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/npc/test_npc_system.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/physics/test_body.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/physics/test_collision.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/physics/test_segment_cast.cpp
        ${PROJECT_SOURCE_DIR}/tests/playtest/test_playtest.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/render/test_actor_sprite.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/render/test_animation.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/render/test_animation_system.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/render/test_camera.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/render/test_camera_shake.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/render/test_cover_fade.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/render/test_level_object_render.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/render/test_presentation.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/render/test_render_scene.cpp
        ${PROJECT_SOURCE_DIR}/tests/scripting/test_lua_npc_script_loading.cpp
        ${PROJECT_SOURCE_DIR}/tests/scripting/test_lua_npc_script_output.cpp
        ${PROJECT_SOURCE_DIR}/tests/scripting/test_lua_npc_script_validation.cpp
        ${PROJECT_SOURCE_DIR}/tests/scripting/test_lua_npc_scripts.cpp
        ${PROJECT_SOURCE_DIR}/tests/scripting/test_lua_npc_world_integration.cpp
        ${PROJECT_SOURCE_DIR}/tests/scripting/test_lua_presentation_script.cpp
        ${PROJECT_SOURCE_DIR}/tests/scripting/test_lua_vec2.cpp
        ${PROJECT_SOURCE_DIR}/tests/support/test_actor_builder.cpp
        ${PROJECT_SOURCE_DIR}/tests/support/test_npc_machine_builder.cpp
        ${PROJECT_SOURCE_DIR}/tests/support/test_tile_map_builder.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/timing/test_fixed_step.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/timing/test_frame_history.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/timing/test_stopwatch.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/world/test_level_exit.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/world/test_level_validation.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/world/test_npc_world_simulation.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/world/test_pickups.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/world/test_sight.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/world/test_tile_map.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/world/test_world.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/world/test_world_inventory.cpp
        ${PROJECT_SOURCE_DIR}/tests/core/world/test_world_simulation.cpp
)
